---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time={{apt_cache_timeout}}
  tags: ['bootstrap']

- name: Apt install required system packages.
  apt: pkg={{item}} state=installed
  tags: ['bootstrap']
  with_items:
    - "zookeeper={{zookeeper_debian_version}}"
    - "zookeeperd={{zookeeper_debian_version}}"

- name: Overwrite myid file
  template: src=myid.j2 dest=/etc/zookeeper/conf/myid
  tags: ['bootstrap', 'deploy']

- name: Overwrite default config file
  template: src=zoo.cfg.j2 dest=/etc/zookeeper/conf/zoo.cfg
  tags: ['bootstrap', 'deploy']

- name: Enable zookeeper service
  become: yes
  command: systemctl enable zookeeper
  when: ansible_service_mgr == 'systemd'
  tags: ['deploy']

- name: Start ZooKeeper
  systemd:
    name: zookeeper
    state: restarted
    daemon_reload: yes
    enabled: yes
  tags: ['deploy']
