---
- include: Debian.yml
  when: ansible_os_family == 'Debian'

- include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Start Zookeeper
  service: name=zookeeper state=started enabled=yes
  tags: deploy

- name: Ensure that Zookeeper has started and keeps running
  service: name=zookeeper state=started
  tags: deploy
  register: zookeeper_running
  until: zookeeper_running.state == 'started' and not zookeeper_running|changed
  retries: 2
  delay: 5

- name: Validate that Zookeeper is running
  fail:
    msg: >
      Service zookeeper has not started as expected, please check its current status or error messages
  when: zookeeper_running.state != 'started' or zookeeper_running|changed
  tags: deploy
